// app/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* 1) Préconnect + CDN Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400&family=Geist+Mono:wght@400&display=swap"
          rel="stylesheet"
        />

        {/* 2) Tailwind via CDN + config inline pour étendre fontFamily */}
        <script src="https://cdn.tailwindcss.com"></script>
        <script
          // ⚠️ dangerouslySetInnerHTML est nécessaire ici pour injecter la config
          dangerouslySetInnerHTML={{
            __html: `
              tailwind.config = {
                theme: {
                  extend: {
                    fontFamily: {
                      geist: ['Geist', 'sans-serif'],
                      'geist-mono': ['Geist Mono', 'monospace'],
                    },
                  }
                }
              }
            `,
          }}
        />
      </head>
      <body className="antialiased font-geist">
        {children}
      </body>
    </html>
  );
}
